#!/bin/ksh

FSCR=`pwd`
FEXE='/gfs/dk12/pkubota/mcgaanne-2.0.0/grh/exec'
varname=PostGridHistory

cpu=1
MEM=10gb
itime=`echo "24*3600" | bc -l`
BUFFER=20480

cat <<EOT1 > ${FEXE}/xmit.sh
#!/usr/bin/ksh
#PBS -l cpunum_prc=$cpu
#PBS -l tasknum_prc=${cpu}
#PBS -l memsz_job=${MEM}
#PBS -l cputim_job=${itime}
#PBS -o tupay:${FSCR}/${varname}.out
#PBS -e tupay:${FSCR}/${varname}.out
#PBS -j o
#
F_RSVTASK=$cpu

OMP_NUM_THREADS=$cpu
F_ERRCNT=1
F_SETBUF=20480
export F_ERRCNT F_SETBUF F_RSVTASK OMP_NUM_THREADS

${FEXE}/${varname} < ${FSCR}/${varname}.nml > ${FSCR}/${varname}_print.out

#
EOT1
qsub -q  Empi -N xmit ${FEXE}/xmit.sh
